Bytearray instead of bytes TypeError fix.
Updated 2 deprecated functions
Under Arch Linux, using Python 3 and wxpython installed with pip3
Any call to pyscreenshot.grab() would return a: 
TypeError: argument 1 must be read-only bytes-like object, not bytearray.
Therefore, adding bytes() to convert myWxImage.GetData() from bytearray to bytes